/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package huimining;

import ca.pfv.spmf.algorithms.frequentpatterns.efim.AlgoEFIM;
import ca.pfv.spmf.algorithms.frequentpatterns.efim.Itemsets;
import static ca.pfv.spmf.test.MainTestEFIM_saveToMemory.fileToPath;
import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MinhQuang
 */
public class HUI_EFIM extends javax.swing.JFrame {

    /**
     * Creates new form HUI_EFIM
     */
    public HUI_EFIM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcPath = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        btnBrowserInput = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRunEFIM = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMinUtil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBrowerOutput = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtOutput = new javax.swing.JTextField();

        fcPath.setCurrentDirectory(new java.io.File("C:\\Users\\MinhQuang\\Desktop\\HUIMINING\\dataset"));
        fcPath.setFileHidingEnabled(true);
        fcPath.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("EFIM FOR FIND HUI");

        jLabel2.setText("Dataset path:");

        txtPath.setForeground(new java.awt.Color(0, 0, 255));
        txtPath.setEnabled(false);

        btnBrowserInput.setText("Browser");
        btnBrowserInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowserInputActionPerformed(evt);
            }
        });

        btnRunEFIM.setText("Run EFIM");
        btnRunEFIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunEFIMActionPerformed(evt);
            }
        });

        jLabel4.setText("Min Utility");

        jLabel5.setForeground(new java.awt.Color(212, 1, 1));
        jLabel5.setText("please type array with comma. ex: 100,200,300");

        btnBrowerOutput.setText("Browser");
        btnBrowerOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowerOutputActionPerformed(evt);
            }
        });

        jLabel6.setText("OuputPath");

        txtOutput.setForeground(new java.awt.Color(22, 1, 212));
        txtOutput.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(152, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPath)
                            .addComponent(txtMinUtil)
                            .addComponent(txtOutput))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBrowerOutput)
                    .addComponent(btnBrowserInput))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnRunEFIM, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrowerOutput)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrowserInput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnRunEFIM, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowserInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowserInputActionPerformed
        // TODO add your handling code here:
        this.fcPath.setVisible(true);
        fcPath.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (this.fcPath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                txtPath.setText(fcPath.getSelectedFile().getCanonicalPath());
            } catch (IOException ioe) {
                JOptionPane.showMessageDialog(fcPath, ioe);
            }
        }
    }//GEN-LAST:event_btnBrowserInputActionPerformed

    private void btnRunEFIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunEFIMActionPerformed

        // TODO add your handling code here:
        String[] utilities = txtMinUtil.getText().split(",");

        for (String minUtilString : utilities) {
            try {
                // the input and output file paths
                String input = txtPath.getText();
                File inputFile = new File(input);
                String outPutFileName = inputFile.getName().replace(".txt", "_" + minUtilString + "_hui.txt");
                // the minutil threshold
                int minutil = Integer.parseInt(minUtilString.trim());
                String output = txtOutput.getText()+"\\" + outPutFileName;
                // Run the EFIM algorithm
                AlgoEFIM algo = new AlgoEFIM();
                Itemsets itemsets = algo.runAlgorithm(minutil, input, output, true, Integer.MAX_VALUE, true);
                // Print statistics
                algo.printStats();

                // Print the itemsets
//                itemsets.printItemsets();
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(HUI_EFIM.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (IOException ex) {
                Logger.getLogger(HUI_EFIM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        JOptionPane.showMessageDialog(null, "Đã lưu file vào: ./output");

    }//GEN-LAST:event_btnRunEFIMActionPerformed

    private void btnBrowerOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowerOutputActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        this.fcPath.setVisible(true);
        fcPath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (this.fcPath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                txtOutput.setText(fcPath.getSelectedFile().getCanonicalPath());
            } catch (IOException ioe) {
                JOptionPane.showMessageDialog(fcPath, ioe);
            }
        }
    }//GEN-LAST:event_btnBrowerOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HUI_EFIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HUI_EFIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HUI_EFIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HUI_EFIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HUI_EFIM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowerOutput;
    private javax.swing.JButton btnBrowserInput;
    private javax.swing.JButton btnRunEFIM;
    private javax.swing.JFileChooser fcPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMinUtil;
    private javax.swing.JTextField txtOutput;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
